pipelines:
  branches:
    master:
      - step:
          services:
            - docker
          deployment: Production
          script:
            - IMAGE=$AWS_ECR_REPOSITORY/$AWS_ECR_REPOSITORY_NAME
            - TAG=$BBITBUCKET_REPO_SLUG-$BITBUCKET_BRANCH
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REPOSITORY
            - docker build -t $IMAGE:$TAG . \
              --build-arg langauge=$LANGUAGE \
              --build-arg apiBaseUrl=$API_BASE_URL \
              --build-arg assetsBaseURL=${ASSETS_BASE_URL} \
              --build-arg apiWebSocketUrl=${API_WEB_SOCKET_URL}
            - docker push $IMAGE:$TAG
    develop:
      - step:
          services:
            - docker
          deployment: Staging
          script:
            - IMAGE=$AWS_ECR_REPOSITORY/$AWS_ECR_REPOSITORY_NAME
            - TAG=$BITBUCKET_REPOSITORY_NAME-$BITBUCKET_BRANCH
            - aws ecr get-login-password --region $AWS_REGION | docker login --username $AWS_ECR_USERNAME --password-stdin $AWS_ECR_REPOSITORY
            - docker build -t $IMAGE:$TAG . \
              --build-arg langauge=$LANGUAGE \
              --build-arg apiBaseUrl=$API_BASE_URL \
              --build-arg assetsBaseURL=${ASSETS_BASE_URL} \
              --build-arg apiWebSocketUrl=${API_WEB_SOCKET_URL}
            - docker push $IMAGE:$TAG