options:
  docker: true
  size: 2x
definitions:
  services:
    docker:
      memory: 2048
pipelines:
  branches:
    master:
      - step:
          name: Docker build and push
          services:
            - docker
          image: atlassian/pipelines-awscli
          deployment: Production
          script:
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REPOSITORY
            - IMAGE=${AWS_ECR_REPOSITORY/cezerin-admin
            - TAG=${BITBUCKET_BRANCH:-$BITBUCKET_TAG}
            - echo $LANGUAGE
            - docker build -t $IMAGE:$TAG . 
              --build-arg langauge=$LANGUAGE
              --build-arg apiBaseUrl=$API_BASE_URL 
              --build-arg assetsBaseURL=$ASSETS_BASE_URL 
              --build-arg apiWebSocketUrl=${API_WEB_SOCKET_URL}
            - docker push $IMAGE:$TAG
    develop:
      - step:
          name: Docker build and push
          services:
            - docker
          image: atlassian/pipelines-awscli
          deployment: Staging
          script:
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REPOSITORY
            - IMAGE=$AWS_ECR_REPOSITORY/cezerin-admin
            - TAG=${BITBUCKET_BRANCH:-$BITBUCKET_TAG}
            - echo $LANGUAGE
            - docker build -t $IMAGE:$TAG . 
              --build-arg langauge=$LANGUAGE 
              --build-arg apiBaseUrl=$API_BASE_URL 
              --build-arg assetsBaseURL=$ASSETS_BASE_URL 
              --build-arg apiWebSocketUrl=$API_WEB_SOCKET_URL
            - docker push $IMAGE:$TAG